// Launch free catalog: 30 Easy, 20 Medium and 10 Hard problems spread across
// the live topic set. This explicit allowlist is stable as the catalog grows;
// newly imported problems default to Plus without changing existing access.
const FREE_PROBLEM_SLUGS = new Set([
    'equal-width-binning',
    'climate-binary-f1',
    'accuracy-score',
    'bag-of-words',
    'climate-minmax-scale',
    'climate-feature-mean',
    'activation-functions',
    'l2-row-normalization',
    'climate-classification-accuracy',
    'compute-f1-score',
    'cosine-similarity',
    'climate-zscore-standardize',
    'climate-robust-median',
    'balanced-class-weights',
    'label-encoding',
    'fintech-binary-f1',
    'confusion-matrix',
    'fintech-minmax-scale',
    'fintech-feature-mean',
    'gradient-clipping',
    'lag-features',
    'fintech-classification-accuracy',
    'hamming-distance',
    'fintech-zscore-standardize',
    'fintech-robust-median',
    'knn-classifier-iris',
    'matrix-multiplication',
    'healthcare-binary-f1',
    'iou-bounding-boxes',
    'healthcare-minmax-scale',
    'climate-knn-classifier',
    'autocorrelation-function',
    'climate-label-entropy',
    'climate-polynomial-features',
    'climate-roc-auc',
    'kfold-cross-validation',
    'bigram-language-model',
    'climate-cosine-retrieval',
    'climate-ols-regression',
    'decision-stump-classifier',
    'dbscan-clustering',
    'fintech-knn-classifier',
    'chi-square-feature-selection',
    'fintech-label-entropy',
    'fintech-polynomial-features',
    'fintech-roc-auc',
    'macro-micro-f1',
    'edit-distance',
    'fintech-cosine-retrieval',
    'fintech-ols-regression',
    'climate-logistic-gradient',
    'climate-dbscan-density',
    'dynamic-time-warping',
    'climate-graph-pagerank',
    'hmm-forward-likelihood',
    'climate-ranking-ndcg',
    'climate-viterbi-decoding',
    'adaboost-stumps',
    'apriori-frequent-itemsets',
    'fintech-logistic-gradient',
]);

module.exports = { FREE_PROBLEM_SLUGS };
